# Generated by Django 2.1.4 on 2018-12-06 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.UUIDField(default=uuid.UUID('567991cd-49c3-4f4c-abf9-f957e30432df'), editable=False)),
                ('product_name', models.CharField(max_length=300)),
                ('product_description', models.TextField()),
                ('product_stock', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
