# Generated by Django 2.1.4 on 2018-12-06 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181206_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('cd54fb04-b73c-4354-8bf6-eddc10eac318'), editable=False),
        ),
    ]
